name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update NPM  # Needed while 14.x, is supported.
        if: ${{ matrix.node-version == '14.x' }}
        run: npm install -g npm@latest
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v2

